source/index.html.md

[SHIP-2509] Adjust docs for feedback API.

---

scripts/publish.sh

I fixed this in my local repo and forgot to commit it.

[NoTicket] Fix deployment script

---

source/index.html.md

[SHIP-3688] Nicks updates + Validation Endpoint

---

source/index.html.md

[SHIP-6153] Add all orgnization related endpoint documentation

---

source/index.html.md

[SHIP-6134] Fix type, remove GET of all names/addresses

---

source/index.html.md

Update the new Org and FileGroups documentation

---

source/index.html.md

Change hierarchy of verbose product data header

---

source/index.html.md

[SHIP-8070] [SHIP-8152] [SHIP-8153] Various docs changes

---

source/index.html.md

Tweaks in docs

---

source/index.html.md

[SHIP-8722] Rename exceptions with user-appropriate language

[SHIP-8722] Rename exceptions with user-appropriate language

---

source/index.html.md

[SHIP-9367] Include clustering updates

---

source/index.html.md

Fix bullet points

---

source/index.html.md

[ship-9426]

---

source/index.html.md

Include product endpoint

---

source/index.html.md

[SHIP-10458]

---

source/index.html.md

lookup code attribute

---

source/index.html.md

PR for updated doc types in vulcan: https://github.com/softdev15/shipamax-vulcan/pull/5913

[WI00581252] Fix: Missing Packing List Docs

---

source/index.html.md

Fix: dispatchPortEta to dischargePortEta

---

source/index.html.md

[WI00602778]

---

source/index.html.md

[WI00581879]

---

source/index.html.md

Renamed products endpoint and removed ClusterScore, Parse and ValidationResult endpoints

WI00624830 - [Tech Debt]: Review API documentation
